# Generated by Django 5.2.4 on 2025-07-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_form_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
