# Generated by Django 5.2.4 on 2025-07-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_google_form_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='google_form_url',
        ),
    ]
